export const GAMEPLAY_TUNING = {
  accentColor: 0x66f5ff,
  accentSoftColor: 0xb9f8ff,
  failureTransitionDelayMs: 140,
  runStatsHistoryLimit: 40,
  immediateRetryWindowMs: 2500,
  debugOverlayEnabled: false,

  input: {
    pointerFollowSharpness: 34,
    pointerFollowMaxSpeed: 17,
    pointerDeadzone: 0.0015,
    keyboardDriftSpeed: 3.8,
    maxX: 1,
    maxVelocityForEffects: 13,
  },

  jump: {
    burstVelocity: 640,
    gravity: 1950,
    maxY: 134,
    cooldownMs: 260,
    tapMaxDurationMs: 170,
    swipeMinDeltaY: 36,
    minAirTimeMs: 90,
  },

  // Legacy phase block kept for backward compatibility with historical stats fields.
  phase: {
    durationMs: 0,
    cooldownMs: 1,
    collisionSaveScoreBonus: 0,
    precisionScoreBonus: 0,
    deathJustAfterWindowMs: 0,
    inputZoneRadiusPx: 0,
    inputZoneOffsetXPx: 0,
    inputZoneOffsetYPx: 0,
  },

  power: {
    fireballDurationMs: 4200,
    missileDurationMs: 3600,
    ghostDurationMs: 2600,
    magnetDurationMs: 3600,
    missileShotEveryMs: 240,
    fireballBreakScore: 35,
    missileBreakScore: 26,
    fireballPickupScore: 24,
    missilePickupScore: 20,
    ghostPickupScore: 18,
  },

  bonus: {
    spawnEveryMs: 780,
    minSpawnEveryMs: 430,
    spawnY: 760,
    shardChance: 0.56,
    fireballChance: 0.11,
    missileChance: 0.08,
    ghostChance: 0.05,
    scoreBurstChance: 0.14,
    shieldChance: 0.06,
    magnetChance: 0.04,
    pickupRadiusNormalized: 0.1,
    magnetPickupRadiusNormalized: 0.2,
    scoreBurstValue: 120,
    shardValue: 10,
  },

  difficulty: {
    rampDurationMs: 52000,
    maxLevel: 14,
    startScrollSpeed: 300,
    maxScrollSpeed: 610,
    startSpawnEveryMs: 730,
    minSpawnEveryMs: 320,
    startGapWidth: 0.64,
    minGapWidth: 0.26,
  },

  spawn: {
    obstacleSpawnY: 760,
    maxGapShiftPerSpawn: 0.44,
    signaturePatternMinLevel: 1,
    lowWallChance: 0.2,
    solidWallChance: 0.38,
    tightGateChance: 0.28,
    breakableWallChance: 0.14,
    authoredWindowSpacingScale: 0.86,
  },

  collision: {
    playerCollisionRadiusNormalized: 0.07,
    horizontalForgivenessNormalized: 0.034,
    verticalWindowPx: 20,
    lowWallJumpClearY: 46,
    breakableJumpClearY: 74,
    despawnY: -120,
  },

  skill: {
    nearMissEdgeThresholdNormalized: 0.038,
    perfectCenterThresholdNormalized: 0.085,
    nearMissBonus: 11,
    perfectPassBonus: 18,
    jumpClearBonus: 15,
    streakDecayOnClean: 1,
    maxStreakForFlow: 10,
    maxFlowScoreMultiplier: 0.55,
    comboTimeoutMs: 1900,
  },

  layout: {
    corridorWidthRatio: 0.82,
    corridorMinWidthPx: 300,
    corridorMaxWidthPx: 480,
    playerBottomOffsetPx: 140,
    playerRadiusPx: 16,
    obstacleBaseThicknessPx: 20,
  },

  motion: {
    playerPulseScale: 1.13,
    playerPulseDurationMs: 60,
    trailCount: 6,
    trailLerp: 0.35,
    trailFlowBoost: 0.36,
    trailVelocityOffsetPx: 14,
    trailVelocityBoost: 0.1,
    trailPhaseBoost: 0.16,
    cameraDriftPx: 12,
    cameraDriftLerp: 0.1,
    cameraVelocityInfluence: 2.2,
    cameraTiltMaxRad: 0.012,
    cameraTiltLerp: 0.11,
    baseZoom: 1,
    speedZoomMax: 0.022,
    flowZoomMax: 0.016,
    phaseZoomBoost: 0,
    zoomLerp: 0.08,
    nearMissFlashDurationMs: 22,
    perfectFlashDurationMs: 38,
    phaseFlashDurationMs: 0,
    collisionFlashDurationMs: 72,
    phaseOrbScaleBoost: 0,
  },

  material: {
    hapticEnabled: true,
    hapticMinIntervalMs: 24,
  },
} as const;
